import Sidebar from './components/Sidebar';
import './globals.css';
import type { Metadata } from 'next';
import { ReduxProvider } from './redux/provider';
import { useState } from 'react';
import clsx from 'clsx';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="en">
      <body className='overflow-x-hidden'>
      <ReduxProvider>
        <div className='wrapper'>
          <Header/>
          <Sidebar />
          <main>{children}</main>
        </div>
      </ReduxProvider>
      </body>
    </html>
  );
}
